name:       customer-feedback-svc
version:    0.1.0.0
license:    MIT
author:     "Max Taldykin"
maintainer: "jorpic@gmail.com"
copyright:  "2020 Max Taldykin"

extra-source-files:
- README.md

description:  Please see the README

ghc-options:
  - -Wall
  - -Werror
  - -O2
  - -funbox-strict-fields

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - DeriveGeneric
  - DeriveAnyClass

executables:
  customer-feedback-svc:
    main: Main.hs
    source-dirs: hs
    dependencies:
      - base >= 4.7 && < 5
      - aeson
      - configurator
      - data-default-class
      - postgresql-simple
      - qm-interpolated-string
      - resource-pool
      - scotty
      - http-types
      - text
      - wai
      - wai-extra
