version: 2

defaults: &defaults
  working_directory: "/carma"
  docker:
    - image: ruamc/carma-stack-build:stack-1.6.5@sha256:f12669a586c621493be9cd08b2751a0ffa89de9a4fa9ffbdb1fd1b4f1068791a

jobs:

  build_client:
    <<: *defaults
    docker:
      - image: node:8.11.1@sha256:26e4c77f9f797c3993780943239fa79419f011dd93ae4e0097089e2145aeaa24
    steps:
      - checkout
      - run:
          name: Node.js and NPM version
          command: |
            printf 'node: %s, npm: %s\n' "`node --version`" "`npm --version`"
      - run:
          name: Build CaRMa frontend
          command: |
            cd srv
            npm install
            npm run prod-build
            npm run build-backend-templates
      - run:
          name: Build CaRMa frontend ("pure" part)
          command: |
            cd srv/resources/assets/pure
            npm install
            git submodule update --init --recursive purescript-react-dropzone
            git submodule update --init --recursive purescript-react-rich-text-editor
            npm run bower -- install --allow-root
            npm run prod-clean-build
      - persist_to_workspace:
          root: .
          paths:
            - ./srv/resources

  build_server:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - stack-cache-{{ checksum "stack.yaml" }}
      - run:
          name: Haskell Stack version
          command: |
            stack --version
      - run:
          name: Build CaRMa backend
          command: |
            stack --install-ghc -j2 build
      - run:
          name: Run tests
          command: |
            cd tools
            stack exec carma-configurator -- -t carma-tools >/dev/null
      - save_cache:
          key: stack-cache-{{ checksum "stack.yaml" }}
          paths:
            - ~/.cabal
            - ~/.ghc
            - ~/.stack
            - .stack-work
      - run:
          name: Build CaRMa backend container
          command: |
            stack image container
            docker save carma > carma-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./carma-image.tar

  build_bundle:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build CaRMa frontend + backend container
          command: |
            docker load < carma-image.tar
            cd srv
            docker build \
              --build-arg VCS_REF=$CIRCLE_SHA1 \
              --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
              -t ruamc/carma-bundle:latest \
              -t ruamc/carma-bundle:${CIRCLE_BRANCH/\//-} \
              -t ruamc/carma-bundle:$CIRCLE_SHA1 \
              .

      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            if [ $CIRCLE_BRANCH = "master" ]; then docker push ruamc/carma-bundle:latest; fi
            docker push ruamc/carma-bundle:${CIRCLE_BRANCH/\//-}
            docker push ruamc/carma-bundle:$CIRCLE_SHA1
            docker logout

workflows:
  version: 2
  build_all:
    jobs:
      - build_client
      - build_server
      - build_bundle:
          requires:
            - build_client
            - build_server
