name:        carma-utils
version:     1.0.0.0
license:     BSD3
author:      Viacheslav Lotsmanov
maintainer:  <lotsmanov89@gmail.com>
category:    Web
synopsis:    Generic utils for CaRMa

description:
  Generic utils for CaRMa used over the CaRMa's packages.

dependencies:
  - base

ghc-options:
  - -Wall
  - -Werror
  - -O2
  - -funbox-strict-fields

library:
  source-dirs: src
